// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package services

import (
	"gin-wire-plate/api/pb"
	"gin-wire-plate/internal/pkg/config"
	"gin-wire-plate/internal/pkg/log"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateProductsService(cf string, detailsSvc pb.DetailsClient, ratingsSvc pb.RatingsClient, reviewsSvc pb.ReviewsClient) (ProductsService, error) {
	viper, err := config.New(cf)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.New(options)
	if err != nil {
		return nil, err
	}
	productsService := NewProductService(logger, detailsSvc, ratingsSvc, reviewsSvc)
	return productsService, nil
}

// wire.go:

var testProviderSet = wire.NewSet(log.ProviderSet, config.ProviderSet, ProviderSet)
